spring:
  application:
    name: footarena-booking-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:mysql://localhost:3306/footarena
    username: ${DB_USERNAME:moha}
    password: ${DB_PASSWORD:azerty}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
      platform: mysql

server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /api

# Configuration JWT
jwt:
  secret: ${JWT_SECRET:footarena-super-secret-key-change-in-production}
  expiration: ${JWT_EXPIRATION:86400} # 24 heures

# Configuration Stripe
stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:}

# Logs
logging:
  level:
    root: INFO
    com.footArena.booking: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# Profil Development
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.footArena.booking: DEBUG

---
# Profil Production
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.footArena.booking: INFO
    org.springframework.web: WARN